# version: "3.8"

services:
  redis:
    image: redis:7
    container_name: fashion-redis
    ports:
      - "6379:6379"

  kestra:
    image: kestra/kestra:latest
    container_name: fashion-kestra
    ports:
      - "8081:8080"   # Kestra UI on localhost:8081
    environment:
      - KESTRA_CONFIGURATION_CLASS=kestra.configuration.LocalConfiguration
